- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes

- name: restart mysqld_exporter
  systemd:
    name: mysqld_exporter
    state: restarted
  when:
    - not keep_service_mysqld_exporter_started.changed